### ISSUE TITLE
Passport Shibboleth

### ISSUE THREAD

**Issue by prabhu** [drstearns/passport-uwshib#1]
Thank you for this wonderful project. I found this a bit specific to your institution. I have done some refactoring, added some tests and have created a new generic passport shibboleth library here.

https://github.com/colearnr/passport-shibboleth

Kindly let me know your thoughts.

Best,
Prabhu

**Comment by drstearns** [comment]
Sorry, I only just now noticed this issue. I'm guessing that you already know this, but my module uses passport-saml to do all the Shibboleth work, so passport-saml already is a generic Shibboleth library. All my module does is default the configuration options for my particular institution, and provide a few handy middleware functions. I built this module so that others at my same institution could quickly build node servers that used our IdP. My institution didn't have any documentation on how to do this, and the configuration options weren't obvious, so packaging this up into a module seemed like a good idea.

Were you not able to use passport-saml directly if you wanted a generic Shibboleth library?
